### ISSUE TITLE
Node-RED node naming guidelines

### ISSUE THREAD

**Issue by hardillb** [arlemi/skyhook-locationRQ-nodered#1]
Could you please rename your npm package to meet the Node-RED naming guidelines outlined at the end of here:

http://nodered.org/docs/creating-nodes/packaging

None core contributed nodes should start with `node-red-contrib-` not `node-red-node-` please so it's obvious they are not maintained by the Node-RED team

Thanks

**Comment by arlemi** [comment]
My bad, I've corrected it.
